name: educagame
description: "Educaçao emocional com Gameficaçao"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  step_progress_indicator: ^1.0.2
  simple_speed_dial: ^0.1.7
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^1.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/
    # - assets/icons/
    - assets/images/
    - assets/images/personagem.svg
    - assets/images/man.png
    - assets/images/cyberbullying.png
    - assets/images/negligencia.png
    - assets/images/toque.png
    - assets/images/segredo.png
    - .env
  fonts:
    - family: BalooThambi
      fonts:
        - asset: assets/fonts/BalooThambi-Regular.ttf
        # - asset: assets/fonts/BalooBhaijaan.ttf
        # - asset: assets/fonts/AbhayaLibre-ExtraBold.ttf
        # - asset: assets/fonts/Inter-Regular.otf
    - family: BalooBhaijaan
      fonts:
        - asset: assets/fonts/BalooBhaijaan.ttf
    - family: InriaSans
      fonts:
        - asset: assets/fonts/inria-sans.regular.ttf
    - family: AbhayaLibre-ExtraBold
      fonts:
        - asset: assets/fonts/AbhayaLibre-ExtraBold.ttf
